### PR TITLE
test runner 선택 view 구현

### PR DESCRIPTION
**Pull request by kangwonji**
scenario 실행 시 test runner를 선택할 수 있는 modal을 띄우고 선택한 runner로 scenario test를 실행하도록 구현

---
This change is [Reviewable](https://reviewable.io/reviews/fadu-a/ftclient-vue/16)

### CODE REVIEW

**Comment by d4vidh** [comment]
@kangwonji 전반적으로 작성한 코드가 매우 깔끔하네요^^. 몇가지 커맨트를 남겼으니 반영해 주길 바랍니다. `yarn lint`도 부탁^^

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---

*[src/views/FioScenarios/FioScenarioList.vue, line 37 at r1](https://reviewable.io/reviews/fadu-a/ftclient-vue/16#-LChGzQY9Y-jJksFUKWF:-LChGzQZ5S8xJI9zNeAT:b-2c7ejo) ([raw file](https://github.com/fadu-a/ftclient-vue/blob/842160c9672558425d9088661ce61f8d0b058320/src/views/FioScenarios/FioScenarioList.vue#L37)):*
> ```Vue
>             variant="danger"
>             size="sm"
>             class="mr-1"
> ```

@kangwonji mr-1은 bootstrap에서 제공하는 css class로 right margin하기 위한 용도입니다. 이 버튼은 맨 오른쪽에 위치하니 해당 class가 없어도 될 것 같아

---

*[src/views/FioScenarios/FioScenarioList.vue, line 113 at r1](https://reviewable.io/reviews/fadu-a/ftclient-vue/16#-LChIbI9Ek5i-GDSNyIz:-LChIbI9Ek5i-GDSNyJ-:b-n7cqul) ([raw file](https://github.com/fadu-a/ftclient-vue/blob/842160c9672558425d9088661ce61f8d0b058320/src/views/FioScenarios/FioScenarioList.vue#L113)):*
> ```Vue
>       ],
>       selected: "",
>       selectedScenarioID: ""
> ```

@kangwonji 선택한 scenario id는 selectedScenarioID, 선택한 runner id는 selected인데 runner에 대해서도 selectedRunnerId로 일관성을 맞췄으면 좋겠습니다. 그리고 selectedScenarioID도 일반적인 js convention인 camelCase로 ㅋ

---

*[src/views/FioScenarios/FioScenarioList.vue, line 141 at r1](https://reviewable.io/reviews/fadu-a/ftclient-vue/16#-LChJYkR5p9UncXWbyH4:-LChJYkR5p9UncXWbyH5:b152he) ([raw file](https://github.com/fadu-a/ftclient-vue/blob/842160c9672558425d9088661ce61f8d0b058320/src/views/FioScenarios/FioScenarioList.vue#L141)):*
> ```Vue
>       this.$root.$emit("bv::show::modal", "modal");
>     },
>     Run(scenario) {
> ```

@kangwonji runner 선택 모달을 띄우는 메소드인데 이름이 Run인게 어색해요. showRunnerModal 등과 같이 동작을 잘 표현할 수 있는 이름을 지었으면 좋겠습니다. 그러고 보니 위의 showTestcases도 의미가 모호하네요 ㅋ 같은 방식으로 변경 부탁해

---


*Comments from [Reviewable](https://reviewable.io/reviews/fadu-a/ftclient-vue/16#-:-LChK9oQBsbqBvDDb-iY:b-lswo65)*

**Comment by d4vidh** [comment]
Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fadu-a/ftclient-vue/16)*

**Comment by kangwonji** [comment]
수정하고  다시 push 했습니다 ~

**Comment by d4vidh** [comment]
:lgtm: merge하겠습니다.

---

Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/fadu-a/ftclient-vue/16#-:-LCl3KJhCceIxqQNjLlQ:b-f19ufw)*

**Pull request merged**
